### ISSUE TITLE
Failed to compile in ./src/assets/sass/siqtheme.scss

### ISSUE THREAD

**Issue by jukillo** [siQuang/siqtheme#1]
Hi mate,

First of all, congrats for this template. Looks like awesome.

Im newbie building this type of templates. 
When i try to dev or prod, i have the same result: 

 ERROR  Failed to compile with 2 errors                                                                                                  19:53:49
 error  in ./src/assets/sass/siqtheme.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.

Can you help me¿? or if you prefer, if you can share a compiled copy of the project will be ideal for me.

Thanks!

**Comment by siQuang** [comment]
Thanks, I rollback Bootstrap v4.4.1 to temp fix the issue. Download the latest v.1.0.8 and compile again. In the next version, I'll have the fix for the latest Bootstrap v.4.5.

**Comment by jukillo** [comment]
Thanks!

Now it compile whithout issues. There are some little 404 when loading dev:

Failed to load resource: the server responded with a status of 404 (Not Found) 
../assets/fonts/vendor/themify-icons-scss/themify.woff?a1ecc3b826d01251edddf29c3e4e1e97
../assets/fonts/vendor/font-awesome/fontawesome-webfont.woff2?af7ae505a9eed503f8b8e6982036873e
../assets/fonts/vendor/themify-icons-scss/themify.ttf?e23a7dcaefbde4e74e263247aa42ecd7
../assets/fonts/vendor/font-awesome/fontawesome-webfont.woff?fee66e712a8a08eef5805a46892932ad
../assets/fonts/vendor/font-awesome/fontawesome-webfont.ttf?b06871f281fee6b241d60582ae9369b9

And this devtools fail:
DevTools failed to load SourceMap: Could not load content for ../public/assets/scripts/simplebar.esm.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I think they are minimal changes, but notifying it costs nothing, ;)

**Comment by siQuang** [comment]
@jukillo I just released v1.0.9 with the fix for fonts path and also upgrade Bootstrap to version 4.5 with the fix for undefined variable.
